version: 2

jobs:
  linux-aarch64:
    working_directory: ~/linux-aarch64
    machine:
      image: ubuntu-2204:current
    # resource_class is what tells CircleCI to use an ARM worker for native arm builds
    #   https://circleci.com/product/features/resource-classes/
    #   https://circleci.com/docs/using-arm/
    resource_class: arm.large
    steps:
      - checkout
          post:
            - git submodule init
            - git submodule update
      - run:
          name: Install build dependencies
          command: |
            sudo apt update
            sudo apt install cmake g++ libopenmpi-dev libhdf5-openmpi-dev hdf5-tools python3 python3-setuptools
            python3 -m pip install -U numpy scipy matplotlib
      - run:
          name: Build
          command: |
            cmake -S . -B build \
              -DAMReX_SPACEDIM=1 -DCMAKE_BUILD_TYPE=Release
            cmake --build build --parallel 4
      - run:
          name: Test
          command: |
            ctest --test-dir build --output-on-failure

workflows:
  version: 2
  all-tests:
    jobs:
      - linux-aarch64
