# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pr:
  autoCancel: true
  branches:
    include:
    - development

pool: avatar

steps:

- task: CMake@1
  displayName: 'Configure CMake'
  inputs:
    cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DAMReX_SPACEDIM=3 -DAMReX_GPU_BACKEND=CUDA -DQUOKKA_PYTHON=OFF -G Ninja'

- script: python ../src/StarCluster/perturbation.py --kmin=2 --kmax=64 --size=128 --alpha=2 --f_solenoidal=1.0
  displayName: 'Run perturbation.py to generate input file for StarCluster test'

- script: mv ../src/StarCluster/zdrv.hdf5 ../tests/
  displayName: 'Move file to tests'

- task: CMake@1
  displayName: 'Build Quokka'
  inputs:
    cmakeArgs: '--build .'

- task: CMake@1
  displayName: 'Run CTest'
  inputs:
    cmakeArgs: '-E chdir . ctest -E "MatterEnergyExchange*" -T Test --output-on-failure'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: cTest
    testResultsFiles: build/Testing/*/Test.xml
    testRunTitle: $(Agent.JobName)
  condition: succeededOrFailed()
  displayName: Publish test results
