# don't run on pull request or push
pr: none
trigger: none

# run on timed schedule, like a cron job
# NOTE: all times are in UTC!
schedules:
- cron: '0 14 * * *'
  displayName: Daily 1am build (AEDT)
  branches:
    include:
    - development

# NOTE: several Python packages are needed for regression_testing to run properly:
#   https://github.com/AMReX-Codes/regression_testing/blob/main/requirements.txt
# ALSO NEEDED: bokeh

jobs:
  - job: GPU_Regression
    pool: avatar
    timeoutInMinutes: 300
    steps:
    - script: ./extern/regression_testing/regtest.py --clean_testdir regression/quokka-tests.ini
      displayName: 'Run regression testing'
    - publish: /home/bwibking/regression-tests/web
      condition: succeededOrFailed()
      artifact: regressionHTMLOutput
      displayName: 'Upload results to Azure Pipelines'
    - script: cd /home/bwibking/regression-tests/web && git add . && git commit -m 'updated results' && git push
      condition: succeededOrFailed()
      displayName: 'Upload results to GitHub Pages'
