name: Post clang-tidy-review comments

on:
  workflow_run:
    # The name field of the lint action
    workflows: [clang-tidy-review]
    types:
      - completed

jobs:
  build:
    # avoid trying to post comments on a merged PR
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
      - uses: ZedThree/clang-tidy-review/post@9a32adc734e10e4d84baa60f2b7d7c021568c527
      # lgtm_comment_body, max_comments, and annotations need to be set on the posting workflow in a split setup
        with:
        # adjust options as necessary
          lgtm_comment_body: ''
          annotations: false
          max_comments: 10
