name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - uses: ZedThree/clang-tidy-review@v0.10.0
      id: review
      with:
        config_file: src/.clang-tidy
        build_dir: build
        apt_packages: gcc-11,g++-11,python3-dev,,python3-numpy,python3-matplotlib,python3-pip,libopenmpi-dev,libhdf5-mpi-dev
        cmake_command: cmake . -B build -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        split_workflow: true

    - uses: actions/upload-artifact@v3
      with:
        name: clang-tidy-review
        path: |
          clang-tidy-review-output.json
          clang-tidy-review-metadata.json
  