name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-clang-tidy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPACK_ROOT: ${{github.workspace}}/spack
      SPACK_URL: https://github.com/spack/spack.git

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Restore Spack cache
      uses: actions/cache@v3
      id: cache-spack
      with:
        path: ${{env.SPACK_ROOT}}
        key: spack

    - name: Install ADIOS2
      if: steps.cache-spack.outputs.cache-hit != 'true'
      run: |
        mkdir -p $SPACK_ROOT
        git clone -c feature.manyFiles=true $SPACK_URL $SPACK_ROOT
        . $SPACK_ROOT/share/spack/setup-env.sh
        spack install adios2
      shell: bash

    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review
      with:
        config_file: src/.clang-tidy
        build_dir: build
        apt_packages: libopenmpi-dev,libhdf5-mpi-dev,python3-dev,python3-numpy,python3-matplotlib
        cmake_command: cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DQUOKKA_PYTHON=ON -DQUOKKA_OPENPMD=ON
        split_workflow: true

    # Uploads an artefact containing clang_fixes.json
    - uses: ZedThree/clang-tidy-review/upload@v0.14.0

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
