name: codespell

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          # this path is specific to Ubuntu
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r .github/workflows/dependencies/requirements.txt

      - name: Run codespell
        run: |
          codespell -I .github/workflows/codespell_ignore.txt, --ignore-words=.github/workflows/codespell_ignore.txt src
